#!/usr/bin/env python3
"""Compute the BlockBench result tables into results/.

Run:  python analysis/build_tables.py

Each output file records the judge configuration and sample set it used.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "analysis"))

from judge_rules import JUDGES_MAJORITY, is_sample_file, majority, rate, target_found
from stats import bootstrap_ci_tier_mean, holm, mcnemar

OUT = ROOT / "results"
JAN = ROOT / "runs" / "2026-01"
MAY = ROOT / "runs" / "2026-05"

MODELS = [
    "claude-opus-4-5", "gemini-3-pro", "gpt-5.2", "deepseek-v3-2",
    "llama-4-maverick", "qwen3-coder-plus", "grok-4-fast",
]
LABEL = {
    "claude-opus-4-5": "Claude Opus 4.5", "gemini-3-pro": "Gemini 3 Pro",
    "gpt-5.2": "GPT-5.2", "deepseek-v3-2": "DeepSeek v3.2",
    "llama-4-maverick": "Llama 4 Maverick", "qwen3-coder-plus": "Qwen3-Coder-Plus",
    "grok-4-fast": "Grok 4.3",
}
TIERS = ["tier1", "tier2", "tier3", "tier4"]
TC_VARIANTS = [
    ("minimalsanitized", "MinS"), ("sanitized", "San"), ("nocomments", "NoC"),
    ("chameleon_medical", "Cha"), ("shapeshifter_l3", "Shp"),
    ("trojan", "Tro"), ("falseProphet", "FalP"),
]
GS_PROMPTS = [
    ("direct", "Direct"), ("context_protocol", "Context"),
    ("context_protocol_cot", "CoT"),
    ("context_protocol_cot_naturalistic", "Naturalistic"),
    ("context_protocol_cot_adversarial", "Adversarial"),
]


def fmt(value: float | None) -> str:
    return "--" if value is None else f"{value:.1f}"


def ds_outcomes(model: str) -> dict[str, dict[str, bool]]:
    """Per-tier majority outcomes keyed by sample id.

    Keyed rather than listed so that paired tests match contract to contract
    instead of relying on two models happening to iterate in the same order.
    """
    per_tier: dict[str, dict[str, bool]] = {}
    for tier in TIERS:
        names: set[str] = set()
        for judge in JUDGES_MAJORITY:
            directory = JAN / "judge" / judge / model / "ds" / tier
            if directory.is_dir():
                names |= {p.name for p in directory.iterdir() if is_sample_file(p)}
        outcomes: dict[str, bool] = {}
        for name in sorted(names):
            verdict = majority([
                target_found(JAN / "judge" / j / model / "ds" / tier / name)
                for j in JUDGES_MAJORITY
            ])
            if verdict is not None:
                outcomes[f"{tier}/{name}"] = verdict
        per_tier[tier] = outcomes
    return per_tier


def gs_slices() -> tuple[set[str], set[str]]:
    """GS-Orig is exactly the sample set carried by the January run."""
    directory = JAN / "judge" / "glm-4.7" / "claude-opus-4-5" / "gs" / "direct"
    orig = {p.name for p in directory.iterdir() if is_sample_file(p)} if directory.is_dir() else set()

    directory = MAY / "judge" / "glm-4.7" / "claude-opus-4-5" / "gs" / "direct"
    allx = {p.name for p in directory.iterdir() if is_sample_file(p)} if directory.is_dir() else set()
    return orig, allx - orig


def gs_rate(run: Path, model: str, prompt: str, keep: set[str] | None,
            judges=("glm-4.7",), rule="complete_only") -> tuple[float | None, int]:
    directory = run / "judge" / judges[0] / model / "gs" / prompt
    if not directory.is_dir():
        return None, 0
    names = {p.name for p in directory.iterdir() if is_sample_file(p)}
    if keep is not None:
        names &= keep
    hits = n = 0
    for name in sorted(names):
        verdict = majority([
            target_found(run / "judge" / j / model / "gs" / prompt / name, rule)
            for j in judges
        ])
        if verdict is None:
            continue
        n += 1
        hits += verdict
    return (100.0 * hits / n if n else None), n


def false_positives() -> dict[str, tuple[int, int, int]]:
    """Flagged count, actual denominator, total findings on the clean set."""
    result = {}
    for model in MODELS:
        directory = MAY / "detection" / model / "negative"
        flagged = n = findings = 0
        if directory.is_dir():
            for path in sorted(p for p in directory.iterdir() if is_sample_file(p)):
                try:
                    pred = json.loads(path.read_text()).get("prediction", {}) or {}
                except (OSError, ValueError):
                    continue
                n += 1
                findings += len(pred.get("vulnerabilities") or [])
                if (pred.get("verdict") or "").lower() == "vulnerable":
                    flagged += 1
        result[model] = (flagged, n, findings)
    return result


def main() -> None:
    OUT.mkdir(exist_ok=True)
    header = (
        "<!-- Generated by analysis/build_tables.py. Do not edit by hand. -->\n"
        f"<!-- Judges: {', '.join(JUDGES_MAJORITY)} -->\n\n"
    )

    # ---- Table 3: DS and TC -------------------------------------------------
    lines = [header, "# Table 3 — Detection Rate on DS and TC\n",
             "Judges: glm-4.7, mimo-v2-flash, mistral-large. 2-of-3 majority vote.\n",
             "Target found = `complete_found OR partial_found`. Run: 2026-01.\n",
             "The DS `Avg` column is the unweighted mean of the four tier rates.\n",
             "\n| Model | T1 | T2 | T3 | T4 | Avg | 95% CI |" + "".join(f" {l} |" for _, l in TC_VARIANTS) + " TC-Avg |",
             "|---|" + "---|" * (6 + 1 + len(TC_VARIANTS) + 1)]
    ds_stats = {}
    for model in MODELS:
        tiers = ds_outcomes(model)
        tier_rates = [
            100.0 * sum(tiers[t].values()) / len(tiers[t]) for t in TIERS if tiers[t]
        ]
        avg = sum(tier_rates) / len(tier_rates) if tier_rates else None
        keyed = {k: v for t in TIERS for k, v in tiers[t].items()}
        lo, hi = bootstrap_ci_tier_mean({t: list(tiers[t].values()) for t in TIERS})
        ds_stats[model] = {"keyed": keyed, "avg": avg}

        tc_rates = []
        cells = []
        for variant, _ in TC_VARIANTS:
            r, _h, _n = rate(JAN / "judge", f"{model}/tc/{variant}")
            cells.append(fmt(r))
            if r is not None:
                tc_rates.append(r)
        tc_avg = sum(tc_rates) / len(tc_rates) if tc_rates else None

        row = [LABEL[model]] + [
            fmt(100.0 * sum(tiers[t].values()) / len(tiers[t]) if tiers[t] else None)
            for t in TIERS
        ]
        row += [fmt(avg), f"[{lo:.0f}--{hi:.0f}]"] + cells + [fmt(tc_avg)]
        lines.append("| " + " | ".join(row) + " |")
    (OUT / "table3_ds_tc.md").write_text("\n".join(lines) + "\n")

    # ---- Table 4 + Table 10: GS slices and the longitudinal pair -----------
    orig, new = gs_slices()
    lines = [header, "# Table 4 — GS by temporal slice (run 2026-05)\n",
             f"Judge: glm-4.7, `complete_found` only. GS-Orig n={len(orig)}, GS-New n={len(new)}.\n",
             "GS-Orig is defined as the sample set carried by the January run, so the\n"
             "two runs are directly comparable on identical contracts.\n",
             "\n| Model | GS-Orig | GS-New | GS-All |", "|---|---|---|---|"]
    for model in MODELS:
        o, _ = gs_rate(MAY, model, "direct", orig)
        n_, _ = gs_rate(MAY, model, "direct", new)
        a, _ = gs_rate(MAY, model, "direct", None)
        lines.append(f"| {LABEL[model]} | {fmt(o)} | {fmt(n_)} | {fmt(a)} |")

    lines += ["\n# Table 10 — Longitudinal: the same contracts, two evaluation dates\n",
              f"Identical {len(orig)} GS contracts, identical direct prompt, identical models\n"
              "and judge. Only the evaluation date differs.\n",
              "\n| Model | Jan 2026 | May 2026 | Change |", "|---|---|---|---|"]
    for model in MODELS:
        j, _ = gs_rate(JAN, model, "direct", orig)
        m, _ = gs_rate(MAY, model, "direct", orig)
        delta = f"+{m - j:.1f}" if (j is not None and m is not None) else "--"
        lines.append(f"| {LABEL[model]} | {fmt(j)} | {fmt(m)} | {delta} |")
    (OUT / "table4_and_10_gs.md").write_text("\n".join(lines) + "\n")

    # ---- GS per prompt ------------------------------------------------------
    lines = [header, "# GS detection rate by prompt setting\n",
             f"Run: 2026-01, all five prompts on the same {len(orig)} GS contracts.\n",
             "Judge: mimo-v2-flash, which is the only one of the three published\n"
             "judges that covers all five prompt settings completely. glm-4.7 did not\n"
             "score the adversarial prompt and covered naturalistic only partially,\n"
             "so it cannot support this comparison.\n",
             "\n| Model |" + "".join(f" {l} |" for _, l in GS_PROMPTS),
             "|---|" + "---|" * len(GS_PROMPTS)]
    for model in MODELS:
        cells = []
        for prompt, _ in GS_PROMPTS:
            r, n = gs_rate(JAN, model, prompt, None, judges=("mimo-v2-flash",))
            cells.append(f"{fmt(r)} (n={n})" if r is not None else "--")
        lines.append(f"| {LABEL[model]} | " + " | ".join(cells) + " |")
    (OUT / "gs_per_prompt.md").write_text("\n".join(lines) + "\n")

    # ---- False positives, with true denominators ---------------------------
    fps = false_positives()
    lines = [header, "# False positive rate on the clean (negative) set\n",
             "Run: 2026-05. Denominators are the contracts actually evaluated,\n"
             "which is **not** 100 for every model.\n",
             "\n| Model | Flagged | Evaluated | FP rate | Findings |", "|---|---|---|---|---|"]
    for model in MODELS:
        flagged, n, findings = fps[model]
        pct = f"{100.0 * flagged / n:.1f}" if n else "--"
        note = "" if n == 100 else f" ⚠ not 100"
        lines.append(f"| {LABEL[model]} | {flagged} | {n}{note} | {pct} | {findings} |")
    (OUT / "fp_rates.md").write_text("\n".join(lines) + "\n")

    # ---- Statistics: bootstrap + McNemar + Holm ----------------------------
    pvals, discord = {}, {}
    for i, a in enumerate(MODELS):
        for b in MODELS[i + 1:]:
            ka, kb = ds_stats[a]["keyed"], ds_stats[b]["keyed"]
            shared = sorted(set(ka) & set(kb))
            p, bb, cc = mcnemar([ka[k] for k in shared], [kb[k] for k in shared])
            key = f"{LABEL[a]} vs {LABEL[b]}"
            pvals[key] = p
            discord[key] = (bb, cc)
    adjusted = holm(pvals)

    lines = [header, "# DS statistics\n",
             "Bootstrap: 1000 resamples, percentile method, 95%, seed 42.\n",
             "Paired test: McNemar with continuity correction on per-contract outcomes.\n",
             "Correction: Holm-Bonferroni over all 21 pairwise comparisons. The original\n"
             "pipeline applied no correction, so raw and adjusted values are both shown.\n",
             "\n| Comparison | b | c | raw p | Holm p | sig. at .05 |",
             "|---|---|---|---|---|---|"]
    for key, p in sorted(pvals.items(), key=lambda kv: kv[1]):
        bb, cc = discord[key]
        lines.append(f"| {key} | {bb} | {cc} | {p:.4f} | {adjusted[key]:.4f} | "
                     f"{'yes' if adjusted[key] < 0.05 else 'no'} |")
    (OUT / "stats_ds.md").write_text("\n".join(lines) + "\n")

    print("wrote:")
    for path in sorted(OUT.glob("*.md")):
        print(f"  {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
